## Property-style Configuration for the Spring Application
## @see http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

## Properties used only in the Spring context ##
server:
  servlet:
    context-path: '/building'

## Logging configuration ##
#logging.file=${spring.application.name}.log

# Spring Bean Settings
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: 'building'
  ## Spring profiles active
  profiles:
    active: local